Support MST 1.4 and 2.0 versions
d4rky-pl/arboris pull request #21
Opened 2018-03-21 13:15 UTC by Rabsztok

Add support for abort function in middleware. For now, both 1.2.1 and >=1.4.0 versions return just `null` as a return value when aborted. Later on, we will add ability to pass custom abort value.

2018-03-22 15:08 UTC, d4rky-pl commented
Please fix the tests first :)

2018-03-22 15:10 UTC, d4rky-pl commented
I believe you're not initializing node_modules properly before running the tests, you will probably have to add setup step (for ex. with `beforeAll` and `child_process.spawn`)

2018-03-22 15:13 UTC, Rabsztok commented
The problem lies with Travis not installing MST versions from package.json
inside tests directory. I will fix that tomorrow.

czw., 22 mar 2018, 16:10 użytkownik Michał Matyas <notifications@github.com>
napisał:

> I believe you're not initializing node_modules properly before running the
> tests, you will probably have to add setup step (for ex. with beforeAll
> and child_process.spawn)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/d4rky-pl/arboris/pull/21#issuecomment-375341462>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACy0mBl00EJUN2Ct9OaSpZJEK3KHBn7dks5tg77zgaJpZM4Szx1y>
> .
>

2018-03-22 17:01 UTC, d4rky-pl commented
Yes, but you would have the same problem if you cloned the repository and ran the tests yourself since `node_modules` is gitignored so it's not only CI issue but incorrect tests setup ;)

2018-03-23 12:56 UTC, Rabsztok commented
It will fix #18 and #20 issues.

2018-03-23 13:00 UTC, d4rky-pl requested changes

2018-03-23 13:00 UTC, d4rky-pl commented on .gitignore
> +__tests__/**/yarn.lock
Since `jest.setup.js` uses npm, this is unnecessary

2018-03-23 13:00 UTC, d4rky-pl commented on src/middleware.js
> +      return abort ? abort(null) : null
Please change this to `typeof abort === 'function'`

2018-03-23 13:00 UTC, d4rky-pl commented on src/middleware.js
> +        return abort ? abort(null) : null
Same as above

2018-03-23 13:00 UTC, d4rky-pl commented on jest.setup.js
> +const mstVersions = ["1.2.1", "1.4.0"]
Please add 1.3.0 and 2.0.0

2018-03-23 13:19 UTC, d4rky-pl approved these changes

2018-03-23 13:19 UTC, merged